/* ------------------------------------------------------------------
   Flight & scenery data
   Each flight references a "theme" that drives the realistic window
   scene (sky colours, clouds, stars, aurora, city lights below...).
-------------------------------------------------------------------*/

const THEMES = {
  cityNight: {
    name: "Lumières des villes",
    skyTop:   [6, 11, 28],
    skyMid:   [16, 26, 58],
    skyHorizon:[42, 50, 92],
    glow:     [120, 110, 180],
    glowStrength: 0.25,
    stars: 1,
    moon: { x:0.74, y:0.2, r:24, glow:1 },
    aurora: 0,
    cloudColor:[40, 48, 78],
    cloudDensity: 0.45,
    cloudAlpha: 0.5,
    ground: "cities",
    wingLights: 1,
  },
  goldenDusk: {
    name: "Coucher doré",
    skyTop:   [22, 28, 64],
    skyMid:   [120, 70, 96],
    skyHorizon:[250, 150, 78],
    glow:     [255, 170, 90],
    glowStrength: 0.9,
    glowX: 0.3,
    stars: 0.35,
    moon: 0,
    aurora: 0,
    cloudColor:[255, 168, 110],
    cloudDensity: 0.75,
    cloudAlpha: 0.7,
    ground: "haze",
    wingLights: 1,
  },
  aurora: {
    name: "Aurores boréales",
    skyTop:   [3, 7, 20],
    skyMid:   [8, 16, 38],
    skyHorizon:[14, 26, 48],
    glow:     [40, 120, 110],
    glowStrength: 0.2,
    stars: 1,
    moon: { x:0.2, y:0.16, r:18, glow:.7 },
    aurora: 1,
    cloudColor:[26, 34, 56],
    cloudDensity: 0.25,
    cloudAlpha: 0.4,
    ground: "snow",
    wingLights: 1,
  },
  oceanMoon: {
    name: "Traversée océane",
    skyTop:   [5, 10, 26],
    skyMid:   [12, 22, 50],
    skyHorizon:[30, 44, 80],
    glow:     [150, 170, 220],
    glowStrength: 0.3,
    glowX: 0.7,
    stars: 1,
    moon: { x:0.7, y:0.22, r:30, glow:1.3 },
    aurora: 0,
    cloudColor:[34, 44, 72],
    cloudDensity: 0.35,
    cloudAlpha: 0.45,
    ground: "ocean",
    wingLights: 1,
  },
  dawnPeaks: {
    name: "Aube sur les sommets",
    skyTop:   [30, 36, 78],
    skyMid:   [150, 110, 140],
    skyHorizon:[255, 190, 165],
    glow:     [255, 200, 170],
    glowStrength: 0.8,
    glowX: 0.5,
    stars: 0.25,
    moon: 0,
    aurora: 0,
    cloudColor:[255, 205, 195],
    cloudDensity: 0.6,
    cloudAlpha: 0.62,
    ground: "mountains",
    wingLights: 1,
  },
};

const FLIGHTS = [
  { from:"GVA", to:"ZRH", city:"Zurich",            min:33, theme:"cityNight" },
  { from:"GVA", to:"CFE", city:"Clermont-Ferrand",  min:33, theme:"goldenDusk" },
  { from:"GVA", to:"MXP", city:"Milan",             min:42, theme:"cityNight" },
  { from:"GVA", to:"KEF", city:"Reykjavík",         min:50, theme:"aurora" },
  { from:"GVA", to:"LIS", city:"Lisbonne",          min:45, theme:"oceanMoon" },
  { from:"GVA", to:"INN", city:"Innsbruck",         min:38, theme:"dawnPeaks" },
];

const HOME_CITY = "Genève";
